// import('nameMF/NameIndex'); // its asynchronously load this code in this file...
// import('ageMF/AgeIndex'); // its asynchronously load this code in this file...
// import('ipMF/IpIndex'); // its asynchronously load this code in this file...

import('./uiLogicImport');

console.log('🚩 container app running... 🚩');